# RECURSION
# DEFINITION
# RECURSION IS A TECHNIQUE WHERE A FUNCTION CALLS ITSELF TO SOLVE A SMALLER VERSION OF THE SAME PROBLEM.

# RECURSIVE FUNCTION
# A RECURSIVE FUNCTION IS A FUNCTION THAT CALLS ITSELF.
# PURPOSE: TO BREAK A LARGE PROBLEM INTO SMALLER PROBLEMS OF THE SAME TYPE.

# BASE CASE
# THE BASE CASE IS THE SMALLEST PROBLEM THAT CAN BE SOLVED DIRECTLY.
# PURPOSE: TO STOP RECURSION.
# WITHOUT A BASE CASE, RECURSION NEVER ENDS.

# RECURSIVE CASE
# THE RECURSIVE CASE IS THE PART WHERE THE FUNCTION CALLS ITSELF WITH A SMALLER INPUT.
# PURPOSE: TO MOVE TOWARD THE BASE CASE.

# CALL STACK
# THE CALL STACK IS A MEMORY AREA THAT STORES ACTIVE FUNCTION CALLS.
# PURPOSE: TO REMEMBER EACH RECURSIVE CALL UNTIL IT FINISHES.

# ACTIVATION RECORD (STACK FRAME)
# AN ACTIVATION RECORD IS THE INFORMATION STORED FOR ONE FUNCTION CALL.
# IT STORES PARAMETERS, LOCAL VARIABLES, CURRENT STATE, AND RETURN LOCATION.
# PURPOSE: TO ALLOW EACH CALL TO HAVE ITS OWN DATA.

# HEAD RECURSION
# THE RECURSIVE CALL HAPPENS FIRST.
# THE WORK IS DONE AFTER THE RECURSIVE CALL RETURNS.
# PURPOSE: USEFUL WHEN WORK NEEDS TO BE DONE WHILE COMING BACK FROM RECURSION.
# MEMORY TRICK: CALL FIRST, WORK LATER.

# TAIL RECURSION
# THE RECURSIVE CALL IS THE LAST OPERATION.
# NO WORK IS LEFT AFTER THE RECURSIVE CALL RETURNS.
# PURPOSE: CAN BE OPTIMIZED IN SOME LANGUAGES TO USE LESS MEMORY.
# MEMORY TRICK: WORK FIRST, CALL LATER.

# NON-TAIL RECURSION
# SOME WORK REMAINS AFTER THE RECURSIVE CALL RETURNS.
# PURPOSE: USED WHEN THE CURRENT CALL NEEDS THE RESULT OF THE SMALLER PROBLEM BEFORE FINISHING ITS WORK.
# MEMORY TRICK: WORK EXISTS AFTER RETURNING.

# TREE RECURSION
# ONE FUNCTION CALL CREATES MULTIPLE RECURSIVE CALLS.
# PURPOSE: TO SOLVE PROBLEMS THAT SPLIT INTO MULTIPLE SUBPROBLEMS.
# EXAMPLES: FIBONACCI, BINARY TREE PROBLEMS.

# BACKTRACKING RECURSION
# A CHOICE IS MADE, EXPLORED, UNDONE, AND THEN ANOTHER CHOICE IS TRIED.
# PURPOSE: TO FIND ALL POSSIBLE SOLUTIONS.
# EXAMPLES: MAZE PATHS, N-QUEENS, SUDOKU.

# RECURSION FLOW
# UNDERSTAND THE PROBLEM.
# IDENTIFY THE SMALLEST POSSIBLE INPUT.
# DEFINE THE BASE CASE.
# DEFINE HOW THE PROBLEM BECOMES SMALLER.
# CREATE THE RECURSIVE CASE.
# ENSURE EVERY CALL MOVES TOWARD THE BASE CASE.
# REACH THE BASE CASE.
# STOP MAKING NEW RECURSIVE CALLS.
# START RETURNING TO PREVIOUS CALLS.
# COMPLETE ANY REMAINING WORK.
# PRODUCE THE FINAL ANSWER.

# COMMON MISTAKES
# MISSING BASE CASE.
# WRONG BASE CASE.
# INPUT DOES NOT MOVE TOWARD THE BASE CASE.
# INFINITE RECURSION.
# STACK OVERFLOW.
# REPEATED CALCULATIONS OF THE SAME SUBPROBLEM.

# GOLDEN FORMULA
# BASE CASE + RECURSIVE CASE + PROGRESS TOWARD BASE CASE = CORRECT RECURSION.

# RECURSION CHECKLIST
# WHAT IS THE BASE CASE?
# HOW IS THE PROBLEM GETTING SMALLER?
# DOES EVERY CALL MOVE TOWARD THE BASE CASE?
# WHAT HAPPENS WHILE RETURNING?
# IS IT HEAD, TAIL, OR NON-TAIL RECURSION?
# WHAT IS THE TIME COMPLEXITY?
# WHAT IS THE SPACE COMPLEXITY?

# PROBLEM 1: STRING TO INTEGER (ATOI)
# CONVERT A STRING INTO A VALID 32-BIT SIGNED INTEGER.
# # STEP 1: SKIP LEADING SPACES
# IGNORE ALL SPACES FROM THE START OF THE STRING.
# # STEP 2: DETERMINE SIGN
# IF '+' IS FOUND → POSITIVE
# IF '-' IS FOUND → NEGATIVE
# OTHERWISE → POSITIVE BY DEFAULT
# # STEP 3: SKIP LEADING ZEROS
# IGNORE ALL ZEROS BEFORE THE ACTUAL NUMBER.
# # STEP 4: READ DIGITS
# READ CONTINUOUS DIGITS FROM LEFT TO RIGHT.
# STOP WHEN:
# - NON-DIGIT IS FOUND
# - END OF STRING IS REACHED
# # STEP 5: HANDLE NO DIGITS
# IF NO DIGITS WERE READ
# RETURN 0
# # STEP 6: BUILD NUMBER
# CONVERT DIGITS INTO INTEGER VALUE.
# # STEP 7: APPLY SIGN
# POSITIVE → NUMBER
# NEGATIVE → -NUMBER
# # STEP 8: CHECK OVERFLOW
# IF NUMBER > 2147483647
# RETURN 2147483647
# IF NUMBER < -2147483648
# RETURN -2147483648
# # STEP 9: RETURN ANSWER
# RETURN FINAL INTEGER.
# # IMPORTANT EDGE CASES
# - EMPTY STRING
# - ONLY SPACES
# - ONLY '+' OR '-'
# - MULTIPLE SIGNS
# - LEADING ZEROS
# - LETTERS BEFORE DIGITS
# - LETTERS AFTER DIGITS
# - OVERFLOW
# - UNDERFLOW
# - NO DIGITS PRESENT
# # TIME COMPLEXITY
# O(N)
# SCAN EACH CHARACTER ONCE.
# # SPACE COMPLEXITY
# O(1)
# ONLY FEW VARIABLES ARE USED.

#BEST UNDERSTANDING METHOD
def Atoi_edge(s):
    #REMOVE SPACES
    s=s.strip()
    #EDGE CASE : EMPTY STRING
    if not s:
        return 0
    #ASSUME SIGN AS POSITIVE
    sign=1
    if s[0]=='-':
        sign=-1
        s=s[1:]
    elif s[0]=='+':
        s=s[1:]
    #HANDLE "+" OR "-"
    if not s:
        return 0
    INT_MAX=2147483647
    INT_MIN=-2147483648
    def Atoi(index,num):
        #BASE CASE TO STOP PROCESS
        if index>=len(s) or not s[index].isdigit():
            return num
        #BUILD NUMBER FLOW
        num=num*10+int(s[index])
        #CHECK OVERFLOW
        if sign==1 and num>INT_MAX:
            return INT_MAX
        if sign==-1 and -num<INT_MIN:
            return abs(INT_MIN)
        return Atoi(index+1,num)
    result=sign*Atoi(0,0)
    if result>INT_MAX:
        return INT_MAX
    if result<INT_MIN:
        return INT_MIN
    return result
print(Atoi_edge("123ABC  "))